from contextlib import asynccontextmanager
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select
import redis.asyncio as redis

from app.core.config import settings
from app.core.db import get_db, async_session_maker
from app.core.users import fastapi_users, auth_backend, UserManager
from fastapi_users_db_sqlalchemy import SQLAlchemyUserDatabase
from app.models import User, UserRead, UserCreate, UserUpdate
from app.routers.games import router as games_router
from app.routers.venues import router as venues_router
from app.routers.bookings import router as bookings_router
from app.routers.payments import router as payments_router
from app.routers.chat import router as chat_router
from app.routers.ratings import router as ratings_router
from app.routers.notifications import router as notifications_router
from app.routers.teams import router as teams_router
from app.routers.social import router as social_router

# ==========================================
# 1. Lifespan / Startup Seeding Logic
# ==========================================
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Check database and seed developer user if empty
    async with async_session_maker() as session:
        try:
            result = await session.execute(select(User))
            first_user = result.scalars().first()
            if not first_user:
                print("No users found. Seeding developer user...")
                user_db = SQLAlchemyUserDatabase(session, User)
                user_manager = UserManager(user_db)
                
                dev_user = UserCreate(
                    email="dev@example.com",
                    password="devpassword123",
                    name="Dev User",
                    skill_level="Intermediate",
                    city="Mumbai"
                )
                # Save user (hashed_password is autogenerated by fastapi-users)
                created_user = await user_manager.create(dev_user, safe=False)
                # Assign admin role to dev user
                created_user.role = "admin"
                session.add(created_user)
                await session.commit()
                print("Developer user seeded successfully!")
        except Exception as e:
            # During migration setup the table might not exist yet, so we ignore failures here
            print(f"Startup seeding skipped or failed: {e}")
            
    # Start the Redis tasks queue worker
    from app.core.queue import start_worker, stop_worker
    start_worker()
    print("Background task queue worker started.")
            
    yield
    
    # Shutdown queue worker
    await stop_worker()
    print("Background task queue worker stopped.")

# ==========================================
# 2. FastAPI Application Setup
# ==========================================
app = FastAPI(
    title=settings.PROJECT_NAME,
    description="Backend service for Turf - Game finder web app",
    version="1.0.0",
    lifespan=lifespan
)

# CORS configuration to allow local Vite frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# 3. Mount fastapi-users Routers
# ==========================================
# Authentication routes (login / logout)
app.include_router(
    fastapi_users.get_auth_router(auth_backend),
    prefix="/auth/jwt",
    tags=["auth"]
)

# Registration route
app.include_router(
    fastapi_users.get_register_router(UserRead, UserCreate),
    prefix="/auth",
    tags=["auth"]
)

# User profile management route
app.include_router(
    fastapi_users.get_users_router(UserRead, UserUpdate),
    prefix="/users",
    tags=["users"]
)

# Games routes
app.include_router(games_router)

# Venues routes
app.include_router(venues_router)

# Bookings routes
app.include_router(bookings_router)

# Payments routes
app.include_router(payments_router)

# Chat routes (WebSocket)
app.include_router(chat_router)

# Ratings routes
app.include_router(ratings_router)

# Notifications routes
app.include_router(notifications_router)

# Teams routes
app.include_router(teams_router)

# Social routes
app.include_router(social_router)

# ==========================================
# 4. Core Endpoints (Health check)
# ==========================================
@app.get("/health", status_code=status.HTTP_200_OK)
async def health_check(db: AsyncSession = Depends(get_db)):
    db_status = "unhealthy"
    redis_status = "unhealthy"
    
    # 1. Check Database connection
    try:
        await db.execute(text("SELECT 1"))
        db_status = "healthy"
    except Exception as e:
        db_status = f"unhealthy: {str(e)}"
        
    # 2. Check Redis connection
    try:
        r = redis.from_url(settings.REDIS_URL, decode_responses=True)
        await r.ping()
        await r.aclose() # Close connection explicitly
        redis_status = "healthy"
    except Exception as e:
        redis_status = f"unhealthy: {str(e)}"
        
    # Return 503 if any service is down
    if db_status != "healthy" or redis_status != "healthy":
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "unhealthy",
                "database": db_status,
                "redis": redis_status
            }
        )
        
    return {
        "status": "healthy",
        "database": db_status,
        "redis": redis_status
    }
