"""add_ratings_and_karma

Revision ID: c2602a87074a
Revises: d092bc1a19d7
Create Date: 2026-06-06 17:37:08.570005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2602a87074a'
down_revision: Union[str, Sequence[str], None] = 'd092bc1a19d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rater_id', sa.Uuid(), nullable=False),
    sa.Column('rated_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['rated_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rater_id', 'rated_id', 'game_id', name='uq_rating_rater_rated_game')
    )
    op.add_column('user', sa.Column('karma', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'karma')
    op.drop_table('rating')
    # ### end Alembic commands ###
