"""add_geolocation

Revision ID: ccb65f0d38e4
Revises: c2602a87074a
Create Date: 2026-06-06 17:44:52.779811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ccb65f0d38e4'
down_revision: Union[str, Sequence[str], None] = 'c2602a87074a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure postgis extension is created
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    # ### end Alembic commands ###
    
    # Populate location for existing venues
    op.execute("UPDATE venue SET location = ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'location')
    # ### end Alembic commands ###
